# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: indexer
networks:
- id: 421614
  start_block: 0
  contracts:
  - name: ChipInFactory
    address:
    - 0x108c416A6Cb34cea4A1C93F749B347e1dE3C65e8
    handler: src/EventHandlers.ts
    events:
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: PoolCreated(uint256 indexed poolId, address indexed poolAddress, address indexed creator, string title, uint256 targetAmount, address targetToken)
    - event: SwapExecuted(uint256 indexed poolId, address indexed targetToken, uint256 usdcAmount, uint256 tokensReceived)
unordered_multichain_mode: true
